### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by Comrade333** [rempopo/CO30_Hedgerow_Hell_1A.WL_Rosche#1]
1) думаю надо бы баррикады поменять на ежики противотанковые, а то против армии РФ, а они машины с трубами в кучу закидывают))))
2)Фенеков побольше бы, сликшом они не вместительные, на 1 сквад надо 3 фенека
если идея в том, шобы при полном слотинге(которого не будет), пехом пацаны датопали, добавь еще парочку шоб  2 сквада могли поместиться

**Comment by OneScheer** [comment]
Добавил два феннека, заменил баррикаду.
