### ISSUE TITLE
Ревью DZN

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO30_Hedgerow_Hell_1A.WL_Rosche#2]
### Mission:
 - [x] 1. General - Title - А чому название миссии с нижними подчеркиваниями?
 - [x] 2. Зачем три зевса?
 - [x] 3. Брифинг - Враждебные: Вместо "Подкрепления" напиши "Ожидаемые подкрепления", а то интриги нет
 - [x] 4. Брифинг - Враждебные: "минометная батарея (Mortars)" заменить на "минометная батарея (позиция Mortars)" 
 - [x] 5. Брифинг - Дружественные силы: "1-й егерьский взвод Anton ВС ФРГ" а на слотинге "Emil 1'6 Platoon Leader"
 - [x] 6. Брифинг  - Замечания: добавь перенос строки между разными замечаниями
 - [x] 7. А зачем открытый леопард стоит?
 - [x] 8. Пофиксить все траншеи
 - [x] 9. По брифингу 2017ый, а дата 2015
 - [x] 10. Добавь стрелков в минометы сразу, а то их закешит потом

### tSF:
 - [x] 1. Опять включрон Editor Unit Behaviour, а в плен брать некого
 - [x] 2. Тебе ж пишут в начале миссии - НО ФАРП СЕТ, почему його немае, а модуль включон в тсф? 

### Gear:
 - [x] 1. Опять AutoRifleman с единым пулеметом?

**Comment by OneScheer** [comment]
" 1. Опять включрон Editor Unit Behaviour, а в плен брать некого"
this setVariable ['dzn_dynai_setBehavior', 'indoor']; - это не относится к юнит бехавиор?

**Comment by OneScheer** [comment]
А что мне делать с ролью пулемётчика тогда?

**Comment by OneScheer** [comment]
Исправил отмеченное, насчёт Editor Unit Behaviour нужны разъяснения. Также непонятно, что делать с ролью пулемётчика.

**Comment by 10Dozen** [comment]
ok
